image: bitswarm/apache-php-webapp:latest

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - env NOKOGIRI_USE_SYSTEM_LIBRARIES=true bundle install
    - composer self-update
    - composer install --dev --prefer-dist

test:
  stage: test
  script:
  - make build
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - make build
  artifacts:
    paths:
    - output_prod
  only:
  - master

