sculpin:
  permalink: pretty
  ignore:
    # Sass code doesn't need to be sent to the live server.
    - "code/sass/"
    # @todo I don't know why the "*" is needed in this path to make the file
    # actually be excluded but it is.
    - "code/config.rb*"
sculpin_content_types:
    posts:
        permalink: blog/:year/:month/:day/:filename/
#sculpin_twig:
  # Sculpin defaults to "_views" as the folder for templates. "code" is used
  # as a parent directory to separate templates/css/js etc from the "content".
  # In a more complex site, the "code" and "content" folders might even be
  # separate git submodules.
 # source_view_paths:
 #   - "code/_views"