# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.
title: Chris Zietlow
subtitle: Goes to 11!

# Global contact information
email: aczietlow@gmail.com

# Sculpin loads assets with permalinks, thus we have to define the base url where the project lives.
url: http://localhost:8000