sculpin:
  permalink: pretty
  ignore:
    # Sass code doesn't need to be sent to the live server.
    - "code/sass/"
sculpin_content_types:
    posts:
        enabled: false
    blogs:
        type: path
        path: blogs/posts
        singular_name: blog
        enabled: true
        permalink: blog/:title/
        taxonomies:
          - tags